import {format} from 'date-fns';
import debug from 'debug';
import fs from 'fs';
import path from 'path';
import {sprintf} from 'sprintf-js';
import GenerateItems from '../../core/app/Services/BalanceTools/CharacterAttributeDataGeneration/v0_0_2/GenerateItems.js';
import GenerateItemsByPattern
    from '../../core/app/Services/BalanceTools/CharacterAttributeDataGeneration/v0_0_2/GenerateItemsByPattern.js';
import ItemAttributeGenerator
    from '../../core/app/Services/BalanceTools/CharacterAttributeDataGeneration/v0_0_2/ItemAttributeGenerator.js';
import HeroCharacterAttributeGenerator from '../../core/app/Services/BalanceTools/HeroCharacterAttributeGenerator.js';
import {TSDB_Recipe, TSDB_RecipeDB} from '../../core/data/ts/recipes.js';
import ContainerInterface from '../../core/source/ContainerInterface.js';
import {DebugNamespaceID} from '../../core/types/enums/DebugNamespaceID.js';
import {ServiceID} from '../../core/types/enums/ServiceID.js';
import {TSDB_Item, TSDB_ItemDB} from '../../core/types/TSDB_Item.js';
import _ from 'lodash';

export const generate_items_by_patterns = (container: ContainerInterface) => {
    let items: TSDB_ItemDB = {};
    let recipes: TSDB_RecipeDB = {};
    let generateItems = new GenerateItemsByPattern(
        container,
        container.get<ItemAttributeGenerator>(ServiceID.ItemAttributeGenerator),
        container.get<HeroCharacterAttributeGenerator>(ServiceID.HeroCharacterAttributeGenerator),
    );
    generateItems.run(items, recipes);

    let time = format(new Date(), 'dd.MM.yyyy_HH_mm_ss');

    let itemsString = JSON.stringify(items);
    let recipesString = JSON.stringify(recipes);

    let itemsFilename = sprintf('auto_generated_equip_%s.json', time);
    let recipesFilename = sprintf('auto_generated_equip_recipes_%s.json', time);
    let itemsDir = './core/data/json';
    let itemsPathname = path.join(itemsDir, itemsFilename);
    let recipesPathname = path.join(itemsDir, recipesFilename);

    let enumItemIDClassname = sprintf('__ItemAutoGeneratedID_%s', _.replace(time, /[.*]/g, ''));

    let enumItemIDStringFilename: string = sprintf('%s.ts', enumItemIDClassname);
    let enumItemIDStringDir: string = './core/data/autogenerated_code';
    let enumItemIDStringPathname = path.join(enumItemIDStringDir, enumItemIDStringFilename);

    let enumIDsString: string = sprintf('export enum %s {\n', enumItemIDClassname);
    // for (let i = 0; i < items.length; i++) {
    for (const key in items) {
        // enumIDsString += sprintf('\t%s = \'%s\',\n', items[i].ID, items[i].ID);
        enumIDsString += sprintf('\t%s = \'%s\',\n', items[key].ID, items[key].ID);
    }
    enumIDsString += '}'

    fs.writeFile(itemsPathname, itemsString, (error) => {
        if (error) {
            console.log('ERROR', error);
            return;
        }

        debug(DebugNamespaceID.Log)(sprintf('Алгоритм by_pattern, v%s.', '0.0.1'));
        debug(DebugNamespaceID.Log)(sprintf('Данные записаны в файл: %s', itemsPathname));
        // debug(DebugNamespaceID.Log)(sprintf('__ItemAutoGeneratedID created: %s', itemsPathname));
        debug(DebugNamespaceID.Log)(sprintf('Предметов создано: %s.', items.length));
    });

    fs.writeFile(recipesPathname, recipesString, (error) => {
        if (error) {
            console.log('ERROR', error);
            return;
        }

        // debug(DebugNamespaceID.Log)(sprintf('Алгоритм by_pattern, v%s.', '0.0.1'));
        debug(DebugNamespaceID.Log)(sprintf('Рецепты записаны в файл: %s', recipesPathname));
        // debug(DebugNamespaceID.Log)(sprintf('__ItemAutoGeneratedID created: %s', itemsPathname));
        debug(DebugNamespaceID.Log)(sprintf('Рецепотов создано: %s.', recipes.length));
    });

    fs.writeFile(enumItemIDStringPathname, enumIDsString, (error) => {
        if (error) {
            console.log('ERROR', error);
            return;
        }

        debug(DebugNamespaceID.Log)(sprintf('__ItemAutoGeneratedID created: %s', enumItemIDStringPathname));
    });
}