// import _auto_generated_equip_db_data from '../../../core/data/json/auto_generated_equip_23.02.2023_09_45_08.json';
// import debug from 'debug';
// import {DebugNamespaceID} from '../../../core/types/enums/DebugNamespaceID.js';
//
// debug(DebugNamespaceID.Debug)('AUTOGENERATED_CODE: items');
//
// export const auto_generated_equip_db_data = _auto_generated_equip_db_data;