export enum EntityID {
    Icon = 'Icon',
    ArmorMaterial = 'ArmorMaterial',
    Currency = 'Currency',
    CharacterAttribute = 'CharacterAttribute',
    EnemyEntity = 'EnemyEntity',
    EnemyConfig = 'EnemyConfig',
    EquipSlot = 'EquipSlot',
    HeroClass = 'HeroClass',
    HeroRole = 'HeroRole',
    Item = 'Item',
    ItemCategory = 'ItemCategory',
    Quality = 'Quality',
    Recipe = 'Recipe',
}