export enum ItemID {
    Wood = 'Wood',
    WoodBoards = 'WoodBoards',

    Coal = 'Coal',

    IronOre = 'IronOre',
    IronBar = 'IronBar',
    CopperOre = 'CopperOre',
    CopperBar = 'CopperBar',
    TinOre = 'TinOre',
    TinBar = 'TinBar',
    BronzeBar = 'BronzeBar',
    GoldOre = 'GoldOre',
    GoldBar = 'GoldBar',

    Herb_1 = 'Herb_1',
    Herb_2 = 'Herb_2',
    Herb_3 = 'Herb_3',

    Cotton = 'Cotton',
    CottonThread = 'CottonThread',
    CottonFabric = 'CottonFabric',
    RabbitSkin = 'RabbitSkin',
    FoxSkin = 'FoxSkin',
    DeerSkin = 'DeerSkin',
    WolfSkin = 'WolfSkin',
    BearSkin = 'BearSkin',
    BoarSkin = 'BoarSkin',
    Leather_01 = 'Leather_01',

    BoarMeat = 'BoarMeat',
    BearMeat = 'BearMeat',

    MagicResources_01 = 'MagicResources_01',
    MagicMaterial_01 = 'MagicMaterial_01',

    PlateHelmet_01 = 'PlateHelmet_01',
    PlateHelmet_02 = 'PlateHelmet_02',
    PlateShoulders_01 = 'PlateShoulders_01',
    PlateBreastplate_01 = 'PlateBreastplate_01',
    PlateBracer_01 = 'PlateBracer_01',
    PlateGloves_01 = 'PlateGloves_01',
    PlateBelt_01 = 'PlateBelt_01',
    PlatePants_01 = 'PlatePants_01',
    PlateBoots_01 = 'PlateBoots_01',

    LeatherHelmet_01 = 'LeatherHelmet_01',
    LeatherShoulders_01 = 'LeatherShoulders_01',
    LeatherBreastplate_01 = 'LeatherBreastplate_01',
    LeatherBracer_01 = 'LeatherBracer_01',
    LeatherGloves_01 = 'LeatherGloves_01',
    LeatherBelt_01 = 'LeatherBelt_01',
    LeatherPants_01 = 'LeatherPants_01',
    LeatherBoots_01 = 'LeatherBoots_01',

    ClothHelmet_01 = 'ClothHelmet_01',
    ClothShoulders_01 = 'ClothShoulders_01',
    ClothBreastplate_01 = 'ClothBreastplate_01',
    ClothBracer_01 = 'ClothBracer_01',
    ClothGloves_01 = 'ClothGloves_01',
    ClothBelt_01 = 'ClothBelt_01',
    ClothPants_01 = 'ClothPants_01',
    ClothBoots_01 = 'ClothBoots_01',

    Shield_01 = 'Shield_01',

    Amulet_01 = 'Amulet_01',
    Ring_01 = 'Ring_01',
    Trinket_01 = 'Trinket_01',

    OneHandedSword_01 = 'OneHandedSword_01',
    TwoHandedSword_01 = 'TwoHandedSword_01',
    Dagger_01 = 'Dagger_01',
    OneHandedAxe_01 = 'OneHandedAxe_01',
    TwoHandedAxe_01 = 'TwoHandedAxe_01',
    Staff_01 = 'Staff_01',
    Wand_01 = 'Wand_01',
    Revolver_01 = 'Revolver_01',

    Stub01 = 'Stub01',
    Stub02 = 'Stub02',
    Stub03 = 'Stub03',
    Stub04 = 'Stub04',
    Stub05 = 'Stub05',
    // Stub06 = 'Stub06',
    // Stub07 = 'Stub07',
    // Stub08 = 'Stub08',
    // Stub09 = 'Stub09',
    // Stub10 = 'Stub10',
}