import {HeroClassID} from '../core/types/enums/HeroClassID.js';

let heroClassIDs = [
    HeroClassID.Tank1,
    HeroClassID.Warrior,
    HeroClassID.Paladin,
    HeroClassID.Tank2,
    HeroClassID.Tank3,
    HeroClassID.Gladiator,
    HeroClassID.Barbarian,
    HeroClassID.PlateDamageDealer1,
    HeroClassID.PlateDamageDealer2,
    HeroClassID.PlateDamageDealer3,
    HeroClassID.LeatherDamageDealer1,
    HeroClassID.Rogue,
    HeroClassID.Archer,
    HeroClassID.LeatherDamageDealer2,
    HeroClassID.Gunslinger,
    HeroClassID.Necromancer,
    HeroClassID.Mage1,
    HeroClassID.Mage2,
    HeroClassID.Warlock,
    HeroClassID.FireMage,
    HeroClassID.Support1,
    HeroClassID.Support2,
    HeroClassID.Support3,
    HeroClassID.Support4,
    HeroClassID.Support5,
]