export enum UI_PanelID {
    Dashboard = 'Dashboard',
    Feed = 'Feed',
    Tavern = 'Tavern',
    ItemStorages = 'ItemStorages',
    Heroes = 'Heroes',
    Locations = 'Locations',
    Production = 'Production',
    DungeonAndRaid = 'DungeonAndRaid',
    Construction = 'Construction',
    Farming = 'Farming',
    Research = 'Research',
    PvP = 'PvP',
    Auction = 'Auction',
    Inbox = 'Inbox',
    Calendar = 'Calendar',
    Guild = 'Guild',
}